export { AboutComponent } from './about/about.component';
export { ContactComponent } from './contact/contact.component';
export { EducationComponent } from './education/education.component';
export { NavBarComponent } from './nav-bar/nav-bar.component';
export { ProjectComponent } from './projects/projects.component';
export { FooterComponent } from './footer/footer.component';
export { ExperienceComponent } from './experience/experience.component';
export { Layout } from './layout';
export { SEO } from './seo';
